import { useState, type FormEvent } from 'react'
import { ArrowUpRight } from 'lucide-react'
import { BrandMark } from '../BrandMark'

export function FinalCTA() {
  const [email, setEmail] = useState('')
  const [message, setMessage] = useState('')
  const subscribe = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!/^\S+@\S+\.\S+$/.test(email)) { setMessage('Enter a valid email address.'); return }; setMessage('Thanks — your place on the fictional NOVA list is saved.') }
  return <section id="cta" className="bg-accent py-20 text-white sm:py-28"><div className="shell grid gap-10 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><p className="eyebrow mb-4 text-white/70">Build a clearer operating rhythm</p><h2 className="max-w-xl text-4xl font-semibold leading-[.95] tracking-[-.075em] sm:text-6xl">Intelligence belongs in the work.</h2><p className="mt-6 max-w-md text-sm leading-relaxed text-white/75">NOVA is a fictional product concept made to show how an excellent team workspace can feel.</p></div><form onSubmit={subscribe} noValidate className="max-w-md lg:justify-self-end"><label className="sr-only" htmlFor="newsletter-email">Work email address</label><div className="flex border-b border-white/60 pb-2"><input id="newsletter-email" type="email" value={email} onChange={(event) => { setEmail(event.target.value); setMessage('') }} placeholder="Your work email" className="focus-ring min-w-0 flex-1 bg-transparent text-base outline-none placeholder:text-white/60" /><button className="focus-ring inline-flex items-center gap-2 text-sm font-bold">Join the list <ArrowUpRight size={16} /></button></div><p className="mt-3 min-h-5 text-xs text-white/80" aria-live="polite">{message}</p></form></div></section>
}

export function Footer() { return <footer data-nav-theme="dark" className="bg-[#111214] py-10 text-white"><div className="shell"><div className="flex flex-col justify-between gap-10 border-b border-white/15 pb-10 sm:flex-row"><div><BrandMark light /><p className="mt-4 max-w-xs text-sm leading-relaxed text-white/55">A fictional AI-powered productivity platform for teams that prefer signal over busywork.</p></div><div className="grid grid-cols-2 gap-x-12 gap-y-2 text-sm text-white/65"><a className="focus-ring hover:text-white" href="#product">Product</a><a className="focus-ring hover:text-white" href="#solutions">Solutions</a><a className="focus-ring hover:text-white" href="#pricing">Pricing</a><a className="focus-ring hover:text-white" href="#faq">Resources</a></div></div><div className="flex flex-col gap-3 pt-5 text-xs text-white/40 sm:flex-row sm:justify-between"><p>© 2026 NOVA. Fictional portfolio project.</p><p>Built with React, TypeScript, Tailwind CSS, GSAP, Lenis, and Lucide.</p></div></div></footer> }
