import { useState } from 'react'
import { Check, ChevronDown, ChevronLeft, ChevronRight, Quote } from 'lucide-react'
import { faqs, pricePlans, testimonials, useCases } from '../../data/site'
import type { UseCaseKey } from '../../data/site'
import { ProductCanvas } from '../ProductCanvas'
import { Reveal } from '../Reveal'
import { SectionHeading } from '../SectionHeading'

const useCaseKeys = Object.keys(useCases) as UseCaseKey[]

export function Solutions() {
  const [active, setActive] = useState<UseCaseKey>('engineering')
  const selected = useCases[active]
  return <section id="solutions" className="py-24 sm:py-32"><div className="shell"><Reveal><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="04 — Solutions" title={<>Workflows that fit<br />how teams move.</>} description="Change the team lens to see how NOVA adapts without turning into another silo." /><div className="flex max-w-md flex-wrap gap-x-4 gap-y-2">{useCaseKeys.map((key) => <button key={key} onClick={() => setActive(key)} className={`focus-ring text-xs ${active === key ? 'font-bold text-accent' : 'text-ink-muted hover:text-foreground'}`} aria-pressed={active === key}>{useCases[key].label}</button>)}</div></div></Reveal><Reveal><div className="mt-12 grid gap-8 border-t border-border pt-8 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="eyebrow text-accent">{selected.label}</p><h3 className="mt-4 text-3xl font-semibold leading-[1.02] tracking-[-.06em]">{selected.title}</h3><p className="mt-5 text-sm leading-relaxed text-ink-muted">{selected.description}</p><ul className="mt-7 space-y-3">{selected.points.map((point) => <li key={point} className="flex items-center gap-2 text-sm"><Check size={15} className="text-accent" />{point}</li>)}</ul><p className="mt-8 font-mono text-xs text-ink-muted"><span className="text-accent">{selected.metric}</span> — fictional team signal</p></div><ProductCanvas view={selected.view} compact /></div></Reveal></div></section>
}

export function Testimonials() {
  const [index, setIndex] = useState(0)
  const testimonial = testimonials[index]
  const previous = () => setIndex((current) => (current + testimonials.length - 1) % testimonials.length)
  const next = () => setIndex((current) => (current + 1) % testimonials.length)
  return <section data-nav-theme="dark" className="bg-[#111214] py-24 text-white sm:py-32"><div className="shell"><Reveal><div className="flex items-end justify-between gap-8"><SectionHeading dark eyebrow="05 — Team notes" title="A calmer way to stay aligned." /><div className="hidden gap-2 sm:flex"><button className="focus-ring grid h-9 w-9 place-items-center border border-white/20 hover:border-white" onClick={previous} aria-label="Previous testimonial"><ChevronLeft size={17} /></button><button className="focus-ring grid h-9 w-9 place-items-center border border-white/20 hover:border-white" onClick={next} aria-label="Next testimonial"><ChevronRight size={17} /></button></div></div><div className="mt-14 grid gap-8 border-t border-white/15 pt-8 lg:grid-cols-[.3fr_1fr]"><Quote size={35} className="text-[#ff73a4]" /><div><p className="max-w-3xl text-3xl font-medium leading-[1.1] tracking-[-.055em] sm:text-4xl">“{testimonial.quote}”</p><div className="mt-9 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-xs font-bold text-black">{testimonial.initials}</span><div><p className="text-sm font-bold">{testimonial.name}</p><p className="text-xs text-white/55">{testimonial.role} <span className="text-white/35">— fictional profile</span></p></div></div><div className="mt-8 flex gap-2 sm:hidden"><button className="focus-ring grid h-9 w-9 place-items-center border border-white/20" onClick={previous} aria-label="Previous testimonial"><ChevronLeft size={17} /></button><button className="focus-ring grid h-9 w-9 place-items-center border border-white/20" onClick={next} aria-label="Next testimonial"><ChevronRight size={17} /></button></div></div></div></Reveal></div></section>
}

export function Pricing() {
  const [yearly, setYearly] = useState(false)
  const monthlyPrice = (price: number) => yearly ? Math.round(price * .8) : price
  return <section id="pricing" className="py-24 sm:py-32"><div className="shell"><Reveal><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><SectionHeading eyebrow="06 — Pricing" title="Start with clarity." description="Illustrative INR plans for a fictional product. Switch to annual pricing to see the planned saving." /><div className="flex items-center gap-1 rounded-sm border border-border bg-surface p-1" role="group" aria-label="Billing frequency"><button onClick={() => setYearly(false)} className={`focus-ring px-3 py-2 text-xs ${!yearly ? 'bg-foreground text-white' : 'text-ink-muted'}`}>Monthly</button><button onClick={() => setYearly(true)} className={`focus-ring px-3 py-2 text-xs ${yearly ? 'bg-foreground text-white' : 'text-ink-muted'}`}>Yearly <span className="ml-1 text-accent">−20%</span></button></div></div></Reveal><div className="mt-12 grid gap-4 lg:grid-cols-3">{pricePlans.map((plan, index) => <Reveal key={plan.name} delay={index * .06}><article className={`flex min-h-[440px] flex-col border p-6 ${plan.featured ? 'border-foreground bg-foreground text-white' : 'border-border bg-surface'}`}><div className="flex items-start justify-between"><div><p className={`eyebrow ${plan.featured ? 'text-[#ff73a4]' : 'text-accent'}`}>{plan.name}</p><p className={`mt-5 text-sm leading-relaxed ${plan.featured ? 'text-white/60' : 'text-ink-muted'}`}>{plan.description}</p></div>{plan.featured && <span className="rounded-full border border-white/20 px-2 py-1 text-[10px]">Recommended</span>}</div><p className="mt-8 text-4xl font-semibold tracking-[-.07em]">₹{monthlyPrice(plan.monthly).toLocaleString('en-IN')}<span className={`ml-1 text-sm font-normal tracking-normal ${plan.featured ? 'text-white/55' : 'text-ink-muted'}`}>/ month</span></p>{yearly && <p className={`mt-2 text-xs ${plan.featured ? 'text-white/55' : 'text-ink-muted'}`}>Billed annually at ₹{(monthlyPrice(plan.monthly) * 12).toLocaleString('en-IN')}</p>}<ul className="mt-8 space-y-3">{plan.features.map((feature) => <li key={feature} className={`flex items-center gap-2 text-sm ${plan.featured ? 'text-white/80' : 'text-ink-muted'}`}><Check size={15} className="text-accent" />{feature}</li>)}</ul><a href="#cta" className={`focus-ring mt-auto block px-4 py-3 text-center text-sm font-bold transition ${plan.featured ? 'bg-accent hover:bg-[#ff4b8b]' : 'border border-foreground hover:bg-foreground hover:text-white'}`}>Choose {plan.name}</a></article></Reveal>)}</div></div></section>
}

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)
  return <section id="faq" className="border-t border-border py-24 sm:py-32"><div className="shell grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><Reveal><SectionHeading eyebrow="07 — Resources" title={<>Questions,<br />answered.</>} description="Everything here is intentionally clear about the fictional, frontend-only scope of NOVA." /></Reveal><div className="border-t border-border"><Reveal>{faqs.map(([question, answer], index) => <div key={question} className="border-b border-border"><button className="focus-ring flex w-full items-center justify-between gap-4 py-5 text-left text-base font-semibold tracking-[-.025em]" onClick={() => setOpenIndex(openIndex === index ? null : index)} aria-expanded={openIndex === index} aria-controls={`faq-panel-${index}`}><span>{question}</span><ChevronDown size={18} className={`shrink-0 transition-transform ${openIndex === index ? 'rotate-180' : ''}`} /></button><div id={`faq-panel-${index}`} className={`grid transition-[grid-template-rows] duration-300 ${openIndex === index ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}><div className="overflow-hidden"><p className="max-w-2xl pb-5 text-sm leading-relaxed text-ink-muted">{answer}</p></div></div></div>)}</Reveal></div></div></section>
}
