import { useState } from 'react'
import { ArrowRight, CircleDot, Sparkles } from 'lucide-react'
import { features, stats } from '../../data/site'
import type { ProductView } from '../../data/site'
import { ProductCanvas } from '../ProductCanvas'
import { Reveal } from '../Reveal'
import { SectionHeading } from '../SectionHeading'

const productTabs: { label: string; view: ProductView }[] = [
  { label: 'Overview', view: 'overview' }, { label: 'Projects', view: 'projects' }, { label: 'AI workspace', view: 'ai' }, { label: 'Analytics', view: 'analytics' },
]

export function TrustedBy() { return <section className="border-b border-border bg-surface py-8"><div className="shell flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><p className="eyebrow text-ink-muted">Illustrative teams, built for modern work</p><div className="flex flex-wrap items-center gap-x-7 gap-y-3 text-sm font-bold tracking-[-.04em] text-[#77756e]"><span>APEX//</span><span>VANTAGE</span><span>morrow</span><span>FIELDWORK</span><span>SYMMETRY</span></div></div></section> }

export function Features() { return <section id="features" className="py-24 sm:py-32"><div className="shell"><Reveal><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><SectionHeading eyebrow="01 — Capabilities" title={<>The operating system<br />for work in motion.</>} description="NOVA keeps the structure around your work clear, while its AI helps turn context into progress." /><p className="max-w-xs text-sm leading-relaxed text-ink-muted">Eight connected capabilities. One calm system for knowing what matters next.</p></div></Reveal><div className="mt-14 grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2 lg:grid-cols-4">{features.map((feature, index) => <Reveal key={feature.title} delay={index * .04}><article className={`group min-h-60 bg-background p-5 transition hover:bg-surface ${index === 0 ? 'lg:col-span-2 lg:row-span-2 lg:min-h-96' : ''}`}><div className="flex items-start justify-between"><feature.icon size={index === 0 ? 26 : 20} strokeWidth={1.5} className="text-accent" /><span className="font-mono text-[10px] text-ink-muted">{feature.number}</span></div><div className={index === 0 ? 'mt-24' : 'mt-14'}><h3 className={`font-semibold tracking-[-.045em] ${index === 0 ? 'text-3xl' : 'text-xl'}`}>{feature.title}</h3><p className="mt-3 max-w-sm text-sm leading-relaxed text-ink-muted">{feature.description}</p></div></article></Reveal>)}</div></div></section> }

export function ProductSection() {
  const [activeTab, setActiveTab] = useState<ProductView>('overview')
  return <section id="product" className="bg-[#111214] py-24 text-white sm:py-32"><div className="shell"><Reveal><div className="grid gap-12 lg:grid-cols-[.78fr_1.22fr] lg:items-end"><SectionHeading dark eyebrow="02 — The product" title={<>One workspace.<br />More context.</>} description="Projects, conversations, decisions, and intelligence belong in the same operational layer." /><div className="space-y-5"><p className="text-sm leading-relaxed text-white/60">NOVA helps teams stop rebuilding a picture of the work every time they need to make a decision.</p><div className="flex flex-wrap gap-x-5 gap-y-2 border-b border-white/15 pb-3">{productTabs.map((tab) => <button key={tab.view} onClick={() => setActiveTab(tab.view)} className={`focus-ring text-xs transition ${activeTab === tab.view ? 'text-white' : 'text-white/45 hover:text-white/80'}`} aria-pressed={activeTab === tab.view}>{tab.label}</button>)}</div></div></div><div className="mt-12"><ProductCanvas view={activeTab} /></div></Reveal></div></section>
}

export function Workflow() { const steps = [['01', 'Connect', 'Bring projects, people, and tools into one shared workspace.'], ['02', 'Organize', 'NOVA understands the shape of the work and who owns it.'], ['03', 'Automate', 'Turn repeated coordination into predictable, lightweight flow.'], ['04', 'Accelerate', 'Use project signals to make a better decision earlier.']]; return <section className="py-24 sm:py-32"><div className="shell"><Reveal><SectionHeading eyebrow="03 — How it works" title={<>From scattered work<br />to clear momentum.</>} /></Reveal><div className="mt-16 grid border-y border-border lg:grid-cols-4">{steps.map(([number, title, description], index) => <Reveal key={number} delay={index * .06} className="relative border-b border-border px-0 py-7 last:border-b-0 lg:border-b-0 lg:border-r lg:px-5 lg:first:pl-0 lg:last:border-r-0"><p className="font-mono text-[10px] text-accent">{number}</p><div className="my-7 flex h-8 items-center"><span className="h-px w-full bg-border" /><CircleDot size={16} className="-ml-1 shrink-0 text-accent" /></div><h3 className="text-xl font-semibold tracking-[-.045em]">{title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-ink-muted">{description}</p></Reveal>)}</div></div></section> }

export function Stats() { return <section className="border-y border-white/10 bg-[#1c1e22] py-14 text-white"><div className="shell"><p className="eyebrow mb-10 text-[#ff73a4]">Illustrative product data</p><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{stats.map((stat, index) => <Reveal key={stat.label} delay={index * .05}><p className="text-4xl font-semibold tracking-[-.07em]">{stat.value}</p><p className="mt-2 text-sm text-white/55">{stat.label}</p></Reveal>)}</div></div></section> }

export function ProductNote() { return <section className="bg-surface py-20"><div className="shell grid gap-8 lg:grid-cols-[1fr_.6fr]"><Reveal><p className="text-3xl font-semibold leading-[1.02] tracking-[-.06em] sm:text-5xl">Work moves faster when the intelligence is built into the workflow—not bolted onto it.</p></Reveal><Reveal delay={.08}><div className="border-l-2 border-accent pl-5"><Sparkles size={18} className="mb-4 text-accent" /><p className="text-sm leading-relaxed text-ink-muted">NOVA is a fictional product concept. Its dashboards, automation, and collaboration patterns are designed to demonstrate a realistic frontend experience.</p><a href="#solutions" className="focus-ring mt-5 inline-flex items-center gap-2 text-sm font-bold">See the team workflows <ArrowRight size={15} /></a></div></Reveal></div></section> }
